var sweety = "Sweety";
var cutie = "Cutie";
console.log("---------Before Swap--------");
console.log(sweety, cutie);
console.log("---------After Swap---------");
var temp = sweety;
sweety = cutie;
cutie = temp;
console.log(sweety, cutie);
console.log("============================");
var num1 = 1000;
var num2 = 2000;
var num3 = 3000;
console.log("---------Before Swap--------");
console.log(num1, num2, num3);
console.log("---------After Swap---------");
var temp = num1;
num1 = num2;
num2 = num3;
num3 = temp;
console.log(num1, num2, num3);
