console.log("Assignments 02.1");
console.log("=====Before Initilization=====");
var bankName;
console.log(bankName, typeof bankName);
console.log("=====After Initilization======");
bankName = "SBI Bank";
console.log(bankName, typeof bankName);
console.log("======Assignments 02.2========");
var marks = `90%`;
console.log(typeof marks);
console.log("====Assignments 02.3====");
console.log("=====Before Initilization=====");
var isWorking;
console.log(isWorking);
console.log("=====After Initilization======");
isWorking = true;
console.log(isWorking);
console.log("=====TypeOf isWorking======");
console.log(typeof isWorking);
console.log("=====Assignments 02.4 a======");
var totalCount = "Hundred and Seven";
console.log(totalCount, typeof totalCount);
console.log("=====Assignments 02.4 b======");
totalCount = 107;
console.log(totalCount, typeof totalCount);
